#!/bin/bash

mkdir -p ParquetData Logs

datasets="GSE10320 GSE62944_Tumor_TPM"

for dataset in $datasets
do
  inFile=TsvData/$dataset/data.tsv
  parquetFile=ParquetData/$dataset.pq
  loadLogFile=Logs/LoadFromTsv.$dataset
  readLogFile=Logs/Read.$dataset

  if [ ! -f $parquetFile ]
  then
    python3 LoadFromTsv.py $dataset $inFile $parquetFile | tee $loadLogFile
  fi

  python3 ReadWrite.py $dataset $parquetFile | tee $readLogFile
#break
done
