#!/bin/bash

datasets="GSE10320 GSE62944_Tumor_TPM"

for dataset in $datasets
do
  python3 LoadFromTsv.py $dataset TsvData/$dataset/data.tsv ParquetData/$dataset.pq
done

#for dataset in $datasets
#do
#  python3 LoadFromTsv.py $dataset
#  break
#done
